[versions]
agp = "9.2.1"
libxposed = "102.0.0"
dexkit = "2.2.0"
shizuku = "13.1.5"

[libraries]
libxposed-api = { module = "io.github.libxposed:api", version.ref = "libxposed" }
libxposed-interface = { module = "io.github.libxposed:interface", version.ref = "libxposed" }
libxposed-service = { module = "io.github.libxposed:service", version.ref = "libxposed" }
dexkit = { module = "org.luckypray:dexkit", version.ref = "dexkit" }
shizuku-api = { module = "dev.rikka.shizuku:api", version.ref = "shizuku" }
shizuku-provider = { module = "dev.rikka.shizuku:provider", version.ref = "shizuku" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
